# Create complete DDD project structure for clothing store management

# Create main directories
$directories = @(
    "src/domain/aggregates/user",
    "src/domain/aggregates/product", 
    "src/domain/aggregates/supplier",
    "src/domain/aggregates/inventory",
    "src/domain/aggregates/order",
    "src/domain/aggregates/financial",
    "src/domain/aggregates/employee",
    "src/domain/value-objects",
    "src/domain/services",
    "src/domain/events",
    "src/domain/repositories",
    "src/domain/specifications",
    "src/domain/factories",
    "src/application/use-cases/user-management",
    "src/application/use-cases/product-management",
    "src/application/use-cases/supplier-management",
    "src/application/use-cases/inventory-management",
    "src/application/use-cases/order-management",
    "src/application/use-cases/financial-management",
    "src/application/use-cases/employee-management",
    "src/application/services",
    "src/application/dtos/user",
    "src/application/dtos/product",
    "src/application/dtos/supplier",
    "src/application/dtos/inventory",
    "src/application/dtos/order",
    "src/application/dtos/financial",
    "src/application/dtos/employee",
    "src/application/mappers",
    "src/infrastructure/database/mongodb/schemas",
    "src/infrastructure/database/mongodb/models",
    "src/infrastructure/database/mongodb/repositories",
    "src/infrastructure/database/mongodb/indexes",
    "src/infrastructure/database/mongodb/migrations",
    "src/infrastructure/external-services/rfid",
    "src/infrastructure/external-services/ai",
    "src/infrastructure/external-services/payment",
    "src/infrastructure/external-services/whatsapp",
    "src/infrastructure/external-services/storage",
    "src/infrastructure/external-services/currency",
    "src/infrastructure/security/authentication",
    "src/infrastructure/security/authorization",
    "src/infrastructure/security/encryption",
    "src/infrastructure/security/audit",
    "src/infrastructure/caching",
    "src/infrastructure/messaging",
    "src/infrastructure/monitoring",
    "src/presentation/http/controllers",
    "src/presentation/http/middleware",
    "src/presentation/http/routes",
    "src/presentation/http/validators",
    "src/presentation/http/transformers",
    "src/presentation/graphql/schema",
    "src/presentation/graphql/resolvers",
    "src/presentation/graphql/dataloaders",
    "src/presentation/websocket/handlers",
    "src/shared/constants",
    "src/shared/utils",
    "src/shared/types",
    "src/shared/errors",
    "src/shared/interfaces",
    "src/config",
    "tests/unit/domain",
    "tests/unit/application",
    "tests/unit/infrastructure",
    "tests/integration/api",
    "tests/integration/database",
    "tests/integration/external-services",
    "tests/e2e/scenarios",
    "tests/fixtures",
    "tests/helpers",
    "scripts",
    "docs/api",
    "docs/architecture",
    "docs/deployment"
)

# Create all directories
foreach ($dir in $directories) {
    New-Item -ItemType Directory -Path $dir -Force
    Write-Host "Created directory: $dir"
}

# Create all files
$files = @(
    # Domain Layer - Aggregates
    "src/domain/aggregates/user/User.ts",
    "src/domain/aggregates/user/UserRole.ts",
    "src/domain/aggregates/user/UserPermission.ts",
    "src/domain/aggregates/user/UserActivity.ts",
    "src/domain/aggregates/product/Product.ts",
    "src/domain/aggregates/product/Article.ts",
    "src/domain/aggregates/product/ProductCategory.ts",
    "src/domain/aggregates/product/ProductCondition.ts",
    "src/domain/aggregates/product/RFIDTag.ts",
    "src/domain/aggregates/product/ProductImage.ts",
    "src/domain/aggregates/supplier/Supplier.ts",
    "src/domain/aggregates/supplier/SupplierContract.ts",
    "src/domain/aggregates/supplier/SupplierRating.ts",
    "src/domain/aggregates/supplier/SupplierBalance.ts",
    "src/domain/aggregates/inventory/Inventory.ts",
    "src/domain/aggregates/inventory/InventoryMovement.ts",
    "src/domain/aggregates/inventory/InventoryLocation.ts",
    "src/domain/aggregates/inventory/Batch.ts",
    "src/domain/aggregates/inventory/StockLevel.ts",
    "src/domain/aggregates/order/Order.ts",
    "src/domain/aggregates/order/OrderItem.ts",
    "src/domain/aggregates/order/OrderStatus.ts",
    "src/domain/aggregates/order/Payment.ts",
    "src/domain/aggregates/order/Shipment.ts",
    "src/domain/aggregates/financial/Invoice.ts",
    "src/domain/aggregates/financial/Transaction.ts",
    "src/domain/aggregates/financial/Currency.ts",
    "src/domain/aggregates/financial/ExchangeRate.ts",
    "src/domain/aggregates/financial/FinancialReport.ts",
    "src/domain/aggregates/employee/Employee.ts",
    "src/domain/aggregates/employee/Attendance.ts",
    "src/domain/aggregates/employee/Shift.ts",
    "src/domain/aggregates/employee/Salary.ts",
    "src/domain/aggregates/employee/EmployeeDocument.ts",
    
    # Value Objects
    "src/domain/value-objects/Money.ts",
    "src/domain/value-objects/Address.ts",
    "src/domain/value-objects/ContactInfo.ts",
    "src/domain/value-objects/DateRange.ts",
    "src/domain/value-objects/Percentage.ts",
    "src/domain/value-objects/Weight.ts",
    "src/domain/value-objects/Dimensions.ts",
    
    # Domain Services
    "src/domain/services/PricingService.ts",
    "src/domain/services/CurrencyConversionService.ts",
    "src/domain/services/RFIDTrackingService.ts",
    "src/domain/services/AIInvoiceProcessingService.ts",
    "src/domain/services/TaxCalculationService.ts",
    "src/domain/services/InventoryAllocationService.ts",
    
    # Domain Events
    "src/domain/events/ProductEvents.ts",
    "src/domain/events/OrderEvents.ts",
    "src/domain/events/InventoryEvents.ts",
    "src/domain/events/FinancialEvents.ts",
    "src/domain/events/EmployeeEvents.ts",
    
    # Repositories Interfaces
    "src/domain/repositories/IUserRepository.ts",
    "src/domain/repositories/IProductRepository.ts",
    "src/domain/repositories/ISupplierRepository.ts",
    "src/domain/repositories/IInventoryRepository.ts",
    "src/domain/repositories/IOrderRepository.ts",
    "src/domain/repositories/IFinancialRepository.ts",
    "src/domain/repositories/IEmployeeRepository.ts",
    
    # Specifications
    "src/domain/specifications/ProductSpecifications.ts",
    "src/domain/specifications/OrderSpecifications.ts",
    "src/domain/specifications/UserSpecifications.ts",
    
    # Factories
    "src/domain/factories/ProductFactory.ts",
    "src/domain/factories/OrderFactory.ts",
    "src/domain/factories/UserFactory.ts",
    
    # Application Layer - Use Cases
    "src/application/use-cases/user-management/CreateUserUseCase.ts",
    "src/application/use-cases/user-management/UpdateUserRoleUseCase.ts",
    "src/application/use-cases/user-management/AuthenticateUserUseCase.ts",
    "src/application/use-cases/user-management/ManagePermissionsUseCase.ts",
    "src/application/use-cases/product-management/CreateProductUseCase.ts",
    "src/application/use-cases/product-management/UpdateProductUseCase.ts",
    "src/application/use-cases/product-management/SortProductsUseCase.ts",
    "src/application/use-cases/product-management/TrackRFIDUseCase.ts",
    "src/application/use-cases/product-management/ProcessArticlesUseCase.ts",
    "src/application/use-cases/supplier-management/RegisterSupplierUseCase.ts",
    "src/application/use-cases/supplier-management/UpdateSupplierBalanceUseCase.ts",
    "src/application/use-cases/supplier-management/RateSupplierUseCase.ts",
    "src/application/use-cases/supplier-management/ProcessSupplierInvoiceUseCase.ts",
    "src/application/use-cases/inventory-management/ReceiveInventoryUseCase.ts",
    "src/application/use-cases/inventory-management/TransferInventoryUseCase.ts",
    "src/application/use-cases/inventory-management/CountInventoryUseCase.ts",
    "src/application/use-cases/inventory-management/AllocateInventoryUseCase.ts",
    "src/application/use-cases/order-management/CreateOrderUseCase.ts",
    "src/application/use-cases/order-management/ProcessPaymentUseCase.ts",
    "src/application/use-cases/order-management/ShipOrderUseCase.ts",
    "src/application/use-cases/order-management/RepeatOrderUseCase.ts",
    "src/application/use-cases/financial-management/ProcessInvoiceUseCase.ts",
    "src/application/use-cases/financial-management/GenerateReportUseCase.ts",
    "src/application/use-cases/financial-management/RecordExpenseUseCase.ts",
    "src/application/use-cases/financial-management/CalculateProfitUseCase.ts",
    "src/application/use-cases/employee-management/RecordAttendanceUseCase.ts",
    "src/application/use-cases/employee-management/CalculateSalaryUseCase.ts",
    "src/application/use-cases/employee-management/ManageShiftsUseCase.ts",
    
    # Application Services
    "src/application/services/NotificationService.ts",
    "src/application/services/WhatsAppIntegrationService.ts",
    "src/application/services/EmailService.ts",
    "src/application/services/ReportingService.ts",
    "src/application/services/ExportService.ts",
    "src/application/services/BackupService.ts",
    
    # Mappers
    "src/application/mappers/UserMapper.ts",
    "src/application/mappers/ProductMapper.ts",
    "src/application/mappers/SupplierMapper.ts",
    "src/application/mappers/OrderMapper.ts",
    "src/application/mappers/FinancialMapper.ts",
    
    # Infrastructure Layer - Database
    "src/infrastructure/database/mongodb/schemas/UserSchema.ts",
    "src/infrastructure/database/mongodb/schemas/ProductSchema.ts",
    "src/infrastructure/database/mongodb/schemas/SupplierSchema.ts",
    "src/infrastructure/database/mongodb/schemas/InventorySchema.ts",
    "src/infrastructure/database/mongodb/schemas/OrderSchema.ts",
    "src/infrastructure/database/mongodb/schemas/FinancialSchema.ts",
    "src/infrastructure/database/mongodb/schemas/EmployeeSchema.ts",
    "src/infrastructure/database/mongodb/schemas/AuditLogSchema.ts",
    "src/infrastructure/database/mongodb/models/index.ts",
    "src/infrastructure/database/mongodb/repositories/MongoUserRepository.ts",
    "src/infrastructure/database/mongodb/repositories/MongoProductRepository.ts",
    "src/infrastructure/database/mongodb/repositories/MongoSupplierRepository.ts",
    "src/infrastructure/database/mongodb/repositories/MongoInventoryRepository.ts",
    "src/infrastructure/database/mongodb/repositories/MongoOrderRepository.ts",
    "src/infrastructure/database/mongodb/repositories/MongoFinancialRepository.ts",
    "src/infrastructure/database/mongodb/repositories/MongoEmployeeRepository.ts",
    "src/infrastructure/database/mongodb/indexes/createIndexes.ts",
    "src/infrastructure/database/mongodb/migrations/001_initial_setup.ts",
    "src/infrastructure/database/mongodb/migrations/002_add_rfid_support.ts",
    "src/infrastructure/database/mongodb/connection.ts",
    
    # External Services
    "src/infrastructure/external-services/rfid/RFIDReaderService.ts",
    "src/infrastructure/external-services/rfid/RFIDWebSocketHandler.ts",
    "src/infrastructure/external-services/rfid/RFIDEventProcessor.ts",
    "src/infrastructure/external-services/ai/GoogleVisionService.ts",
    "src/infrastructure/external-services/ai/AWSTextractService.ts",
    "src/infrastructure/external-services/ai/AzureFormRecognizerService.ts",
    "src/infrastructure/external-services/ai/AIServiceFactory.ts",
    "src/infrastructure/external-services/payment/StripeService.ts",
    "src/infrastructure/external-services/payment/PayPalService.ts",
    "src/infrastructure/external-services/payment/MultiCurrencyProcessor.ts",
    "src/infrastructure/external-services/whatsapp/WhatsAppBusinessAPI.ts",
    "src/infrastructure/external-services/whatsapp/MessageTemplates.ts",
    "src/infrastructure/external-services/whatsapp/WebhookHandler.ts",
    "src/infrastructure/external-services/storage/S3StorageService.ts",
    "src/infrastructure/external-services/storage/LocalStorageService.ts",
    "src/infrastructure/external-services/storage/ImageOptimizationService.ts",
    "src/infrastructure/external-services/currency/ExchangeRateAPIService.ts",
    "src/infrastructure/external-services/currency/CurrencyLayerService.ts",
    
    # Security
    "src/infrastructure/security/authentication/JWTService.ts",
    "src/infrastructure/security/authentication/RefreshTokenService.ts",
    "src/infrastructure/security/authentication/TwoFactorAuthService.ts",
    "src/infrastructure/security/authorization/RBACService.ts",
    "src/infrastructure/security/authorization/PermissionChecker.ts",
    "src/infrastructure/security/authorization/ResourceGuard.ts",
    "src/infrastructure/security/encryption/EncryptionService.ts",
    "src/infrastructure/security/encryption/HashingService.ts",
    "src/infrastructure/security/audit/AuditLogger.ts",
    "src/infrastructure/security/audit/SecurityEventLogger.ts",
    
    # Caching, Messaging, Monitoring
    "src/infrastructure/caching/RedisService.ts",
    "src/infrastructure/caching/CacheManager.ts",
    "src/infrastructure/caching/CacheStrategies.ts",
    "src/infrastructure/messaging/EventBus.ts",
    "src/infrastructure/messaging/MessageQueue.ts",
    "src/infrastructure/messaging/DomainEventPublisher.ts",
    "src/infrastructure/monitoring/MetricsCollector.ts",
    "src/infrastructure/monitoring/HealthCheckService.ts",
    "src/infrastructure/monitoring/PerformanceMonitor.ts",
    
    # Presentation Layer
    "src/presentation/http/controllers/AuthController.ts",
    "src/presentation/http/controllers/UserController.ts",
    "src/presentation/http/controllers/ProductController.ts",
    "src/presentation/http/controllers/SupplierController.ts",
    "src/presentation/http/controllers/InventoryController.ts",
    "src/presentation/http/controllers/OrderController.ts",
    "src/presentation/http/controllers/FinancialController.ts",
    "src/presentation/http/controllers/EmployeeController.ts",
    "src/presentation/http/controllers/ReportController.ts",
    "src/presentation/http/controllers/WebhookController.ts",
    "src/presentation/http/middleware/AuthenticationMiddleware.ts",
    "src/presentation/http/middleware/AuthorizationMiddleware.ts",
    "src/presentation/http/middleware/ValidationMiddleware.ts",
    "src/presentation/http/middleware/ErrorHandlingMiddleware.ts",
    "src/presentation/http/middleware/RateLimitingMiddleware.ts",
    "src/presentation/http/middleware/LoggingMiddleware.ts",
    "src/presentation/http/middleware/CORSMiddleware.ts",
    "src/presentation/http/middleware/SecurityMiddleware.ts",
    "src/presentation/http/routes/index.ts",
    "src/presentation/http/routes/authRoutes.ts",
    "src/presentation/http/routes/userRoutes.ts",
    "src/presentation/http/routes/productRoutes.ts",
    "src/presentation/http/routes/supplierRoutes.ts",
    "src/presentation/http/routes/inventoryRoutes.ts",
    "src/presentation/http/routes/orderRoutes.ts",
    "src/presentation/http/routes/financialRoutes.ts",
    "src/presentation/http/routes/employeeRoutes.ts",
    "src/presentation/http/routes/reportRoutes.ts",
    "src/presentation/http/routes/webhookRoutes.ts",
    "src/presentation/http/validators/userValidators.ts",
    "src/presentation/http/validators/productValidators.ts",
    "src/presentation/http/validators/orderValidators.ts",
    "src/presentation/http/validators/financialValidators.ts",
    "src/presentation/http/transformers/ResponseTransformer.ts",
    "src/presentation/http/transformers/PaginationTransformer.ts",
    "src/presentation/websocket/handlers/RFIDHandler.ts",
    "src/presentation/websocket/handlers/NotificationHandler.ts",
    "src/presentation/websocket/handlers/LiveTrackingHandler.ts",
    "src/presentation/websocket/SocketManager.ts",
    
    # Shared
    "src/shared/constants/ErrorCodes.ts",
    "src/shared/constants/Permissions.ts",
    "src/shared/constants/Roles.ts",
    "src/shared/constants/Categories.ts",
    "src/shared/constants/Countries.ts",
    "src/shared/constants/Currencies.ts",
    "src/shared/utils/DateUtils.ts",
    "src/shared/utils/StringUtils.ts",
    "src/shared/utils/NumberUtils.ts",
    "src/shared/utils/ValidationUtils.ts",
    "src/shared/utils/FileUtils.ts",
    "src/shared/types/index.ts",
    "src/shared/types/CommonTypes.ts",
    "src/shared/types/APITypes.ts",
    "src/shared/errors/BaseError.ts",
    "src/shared/errors/DomainError.ts",
    "src/shared/errors/ApplicationError.ts",
    "src/shared/errors/InfrastructureError.ts",
    "src/shared/interfaces/IService.ts",
    "src/shared/interfaces/IRepository.ts",
    "src/shared/interfaces/IUseCase.ts",
    
    # Config
    "src/config/database.config.ts",
    "src/config/server.config.ts",
    "src/config/security.config.ts",
    "src/config/services.config.ts",
    "src/config/cache.config.ts",
    "src/config/logging.config.ts",
    
    # App Bootstrap
    "src/app.ts",
    "src/server.ts",
    
    # Tests
    "tests/fixtures/users.ts",
    "tests/fixtures/products.ts",
    "tests/fixtures/orders.ts",
    "tests/helpers/testDatabase.ts",
    "tests/helpers/testServer.ts",
    
    # Scripts
    "scripts/seed-database.ts",
    "scripts/migrate-database.ts",
    "scripts/generate-types.ts",
    "scripts/backup-database.ts",
    "scripts/clean-logs.ts",
    
    # Documentation
    "docs/api/swagger.yaml",
    "docs/api/postman-collection.json",
    "docs/architecture/domain-model.md",
    "docs/architecture/use-cases.md",
    "docs/architecture/database-schema.md",
    "docs/deployment/docker-setup.md",
    "docs/deployment/kubernetes-setup.md",
    
    # Environment files
    ".env.example",
    ".env.development",
    ".env.test",
    ".env.production",
    
    # Configuration files
    ".gitignore",
    ".eslintrc.js",
    ".prettierrc",
    "tsconfig.json",
    "package.json",
    "docker-compose.yml",
    "Dockerfile",
    "README.md"
)

# Create all files
foreach ($file in $files) {
    New-Item -ItemType File -Path $file -Force
    Write-Host "Created file: $file"
}

Write-Host "Project structure created successfully!" 